services:
  sector1:
    build:
      context: .
      dockerfile: Sectors/Dockerfile
    container_name: sector1
    restart: always 
    environment:
      - SECTOR_ID=sector1
      - BIND_ADDR=0.0.0.0:5001
      - PEERS=192.168.0.95:5001,192.168.0.98:5002
      - DATA_DIR=/tmp/raft-sector1
      - HTTP_PORT=7001
    ports:
      - "5001:5001"
      - "7001:7001"
    volumes:
      - raft-data-1:/tmp/raft-sector1

volumes:
  raft-data-1:
